### ISSUE TITLE
pretrain

### ISSUE THREAD

**Issue by feifei123feifei** [lygsbw/segdeformer#3]

**Comment by feifei123feifei** [comment]
Hello, will pre-training weights be published?

**Comment by lygsbw** [comment]
Hello,

All the pre-training weights we used are from [MMSegmentation](https://github.com/open-mmlab/mmsegmentation).

Here are some important links:
https://github.com/open-mmlab/mmsegmentation/tree/master/configs/vit
https://github.com/open-mmlab/mmsegmentation/tree/master/configs/swin
https://github.com/open-mmlab/mmsegmentation/tree/master/configs/segformer (Note that we use the old pretrained model (20210726version). Details are included in this [link](https://github.com/open-mmlab/mmsegmentation/pull/1705).)
